/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e29af54f4280a5b376a37d6e4caa643b)
interface __BaseEnv_Env {
	AI: Ai;
	OPENROUTER_MODEL: "";
	WORKERS_AI_MODEL: "";
	STT_WHISPER_URL: "";
	OPENROUTER_API_KEY: string;
	MODEL_PROVIDER: string;
	STT_PROVIDER: string;
	ProjectHub: DurableObjectNamespace<import("./src/index").ProjectHub>;
	GroupChat: DurableObjectNamespace<import("./src/index").GroupChat>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ProjectHub" | "GroupChat";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_MODEL" | "WORKERS_AI_MODEL" | "STT_WHISPER_URL" | "OPENROUTER_API_KEY" | "MODEL_PROVIDER" | "STT_PROVIDER">> {}
}
