/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts`
interface __BaseEnv_Env {
  ProjectHub: DurableObjectNamespace<import("./src/index").ProjectHub>;
  GroupChat: DurableObjectNamespace<import("./src/index").GroupChat>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ProjectHub" | "GroupChat";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
