/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 6569afafe7364f1c747f78bc5bcd5114)
interface __BaseEnv_Env {
	AI: Ai;
	OPENROUTER_API_KEY: string;
	ProjectHub: DurableObjectNamespace<import("./src/index").ProjectHub>;
	GroupChat: DurableObjectNamespace<import("./src/index").GroupChat>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ProjectHub" | "GroupChat";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_API_KEY">> {}
}
